highlighter: pygments
relative_permalinks: false
gauges_id: xxx
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/jekyll/jekyll
baseurl: /frokyll
